#This action is centrally managed in https://github.com/asyncapi/.github/
#Don't make changes to this file in this repo as they will be overwritten with changes made to the same file in above mentioned repo
#It does magic only if there is package.json file in the root of the project
name: Version bump - if Node.js project

on: [release]

jobs:
  version_bump:
    name: Generate assets and bump
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        run: echo ${{ github.event.release.target_commitish }} ${{ github.event.release.type }} ${{ github.event.release.action }} ${{ github.event.action }}
