on:
  workflow_dispatch:
    inputs:
      time:
        description: 'Info about meeting hour in UTC time zone, like: 08 or 16. No PM or AM versions.'
        required: true
      date:
        description: 'Date in a form like: 2022-04-05 where 04 is a month and 05 is a day number.'
        required: true
        
name: Create an issue on push

jobs:
  stuff:
    env:
      MEETING_TITLE: 'test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FULL_DATE: '2022-04-05T08:00:00Z'
          DATE_ONLY: '${{ github.event.inputs.date }}'
        with:
          filename: .github/some-other-template.md
          
