name: Schedule Community Meeting

on:
  workflow_dispatch:
    inputs:
      time:
        description: 'Info about meeting hour in UTC time zone, like: 08 or 16. No PM or AM versions.'
        required: true
      date:
        description: 'Date in a form like: 2022-04-05 where 04 is a month and 05 is a day number.'
        required: true

jobs:

  setup-community-meeting:
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      MEETING_NAME: Community Meeting
      MEETING_DESC: This is a community meeting to regularly talk in open about important topics around AsyncAPI Initiative.
      ZOOM_API_KEY: ${{ secrets.ZOOM_API_KEY }}
      ZOOM_API_SECRET: ${{ secrets.ZOOM_API_SECRET }}
      HOST: lpgornicki@gmail.com
      ALTERNATIVE_HOSTS: fmvilas@gmail.com
      STREAM_URL: ${{ secrets.STREAM_URL }}
      STREAM_KEY: ${{ secrets.STREAM_KEY }}
      CALENDAR_ID: ${{ secrets.CALENDAR_ID }}
      CALENDAR_SERVICE_ACCOUNT: ${{ secrets.CALENDAR_SERVICE_ACCOUNT }}
    name: Setup Community meeting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Install deps
        run: npm install
        working-directory: ./.github/workflows/event_issue_templates
      - name: Create zoom meeting
        uses: actions/github-script@v4
        id: zoom
        with:
          script: |
            const setupZoom = require('./.github/workflows/event_issue_templates/zoom/index.js');
            setupZoom('${{env.MEETING_NAME}}', '${{ github.event.inputs.date }}', '${{ github.event.inputs.time }}', '${{env.HOST}}', '${{env.ALTERNATIVE_HOSTS}}');
      - name: Create issue with meeting details
        uses: JasonEtco/create-an-issue@v2
        id: create-issue
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          FULL_DATE: '${{ github.event.inputs.date }}T${{ github.event.inputs.time }}:00:00Z'
          DATE_ONLY: '${{ github.event.inputs.date }}'
          ZOOM_LINK: '${{steps.zoom.outputs.meetingUrl}}'
        with:
          filename: .github/workflows/event_issue_templates/meetings/community.md
      - name: Create Google Calendar entry
        uses: actions/github-script@v4
        with:
          script: |
            const { addEvent } = require('./.github/workflows/event_issue_templates/calendar/index.js');
            addEvent('${{env.MEETING_NAME}}', '${{env.MEETING_DESC}}', '${{ github.event.inputs.date }}'', '${{ github.event.inputs.time }}'', '${{steps.zoom.outputs.meetingUrl}}', '${{ steps.create-issue.outputs.number }}'')