name: Schedule X Template Workflow

on:
  workflow_call:

    inputs:
      time:
        description: 'Info about meeting hour in UTC time zone, like: 08 or 16. No PM or AM versions.'
        required: true
        type: string
      date:
        description: 'Date in a form like: 2022-04-05 where 04 is a month and 05 is a day number.'
        required: true
        type: string
      meeting_name:
        description: 'Name of the meeting.'
        required: true
        type: string
      meeting_name_suffix:
        description: 'Optional additional description added at the end of meeting title to indicate purpose of given meeting.'
        type: string
        required: false
      meeting_desc:
        description: 'Description of the purpose of the meeting.'
        required: true
        type: string
      host:
        description: 'Email address of the host of the meeting.'
        required: true
        type: string
      alternative_host:
        description: 'Email address of alternative hosts of the meeting.'
        required: true
        type: string
      issue_template_path:
        description: 'Path to the issue template used to create meeting GH issue.'
        required: true
        type: string
      create_zoom:
        description: 'Boolean information if meeting.'
        required: true
        type: boolean

    secrets:
      GH_TOKEN: 
        required: true
      ZOOM_API_KEY:
        required: true
      ZOOM_API_SECRET:
        required: true
      STREAM_URL:
        required: true
      STREAM_KEY:
        required: true
      CALENDAR_ID: 
        required: true
      CALENDAR_SERVICE_ACCOUNT:
        required: true

jobs:

  setup-meeting:
    name: Setup meeting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Install deps
        run: npm install
        working-directory: ./.github/workflows/create-event-helpers
      - if: inputs.create_zoom == true
        name: Create zoom meeting
        uses: actions/github-script@v4
        id: zoom
        with:
          script: |
            const setupZoom = require('./.github/workflows/create-event-helpers/zoom/index.js');
            setupZoom(${{ inputs.meeting_name }}, ${{ inputs.date }}, ${{ inputs.time }}, ${{ inputs.host }}, ${{ inputs.alternative_host }});
      - name: Create issue with meeting details
        uses: JasonEtco/create-an-issue@v2
        id: create-issue
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          FULL_DATE: ${{ inputs.date }}T${{ inputs.time }}:00:00Z
          DATE_ONLY: ${{ inputs.date }}
          TITLE_SUFFIX: ${{ inputs.meeting_name_suffix }}
          ZOOM_LINK: ${{ steps.zoom.outputs.meetingUrl }}
        with:
          filename: ${{ inputs.issue_template_path }}
      - name: Create Google Calendar entry
        uses: actions/github-script@v4
        with:
          script: |
            const { addEvent } = require('./.github/workflows/create-event-helpers/calendar/index.js');
            addEvent(${{ inputs.meeting_name }}, ${{ inputs.meeting_name_suffix }}, ${{ inputs.meeting_desc }}, '${{ steps.zoom.outputs.meetingUrl }}', ${{ inputs.date }}, ${{ inputs.time }}, '${{ steps.create-issue.outputs.number' }})