name: Release

on:
  push:
    branches:
      - master
      - '**-release'
 
jobs:
  release:
    name: 'Release to GitHub' 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repoddd
        uses: actions/checkout@v2 
      - name: Setup Node.jsr
        uses: actions/setup-node@v1
      - name: Add plugin for conventional commits
        run: npm install conventional-changelog-conventionalcommits
      - name: Release to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: asyncapi-bot
          GIT_AUTHOR_EMAIL: info@asyncapi.io
          GIT_COMMITTER_NAME: asyncapi-bot
          GIT_COMMITTER_EMAIL: info@asyncapi.io
        run: npx semantic-release@17.4.3
