#This action is centrally managed in https://github.com/asyncapi/.github/
#Don't make changes to this file in this repo as they will be overwritten with changes made to the same file in above mentioned repo
name: 'Notify slack that there is a new issue or a PR'

on:
    issues:
        types:
            - opened
    pull_request:
        types:
            - opened

jobs:

    slack:
        name: Slack - notify on every new issue or PR
        runs-on: ubuntu-latest
        steps:
            - if: github.event_name == 'issues' && github.actor != 'asyncapi-bot' && github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]'
              name: Send info about issue
              uses: Ilshidur/action-slack@2.0.2
              env:
                SLACK_WEBHOOK: ${{ secrets.SLACK_GITHUB_NEWISSUEPR }}
                SLACK_CUSTOM_PAYLOAD: '{"text":"Custom payload from {{ GITHUB_REPOSITORY }} \\n *with* `new` _line_ escaped","username": "${{github.actor}}"}'
            - if: github.event_name == 'pull_request' && github.actor != 'asyncapi-bot' && github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]'
              name: Send info about pull request
              uses: someimportantcompany/github-actions-slack-message@v1
              with:
                webhook-url: ${{ secrets.SLACK_GITHUB_NEWISSUEPR }}
                text: |
                    New pull request 💪 by {{github.actor}}
                    Title: ${{github.event.pull_request.title}}
                    Details:
                    ${{github.event.pull_request.body}}
                color: info
