name: 'Notify Slack that there is a new issue or a PR'

on:
    issues:
        types:
            - opened
    pull_request:
        types:
            - opened

jobs:

    slack:
        name: Slack - notify on every new issue or PR
        runs-on: ubuntu-latest
        steps:
          - run: echo {{github.type}}
