#This action is centrally managed in https://github.com/asyncapi/.github/
#Don't make changes to this file in this repo as they will be overwritten with changes made to the same file in above mentioned repo
name: 'Notify slack that there is a new issue or a PR'

on:
    issues:
        types:
            - opened
    pull_request:
        types:
            - opened

jobs:

    slack:
        name: Slack - notify on every new issue or PR
        runs-on: ubuntu-latest
        steps:
            - if: github.event_name == 'issues' && github.actor != 'asyncapi-bot' && github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]'
              name: Send info about issue
              uses: rtCamp/action-slack-notify@v2
              env:
                SLACK_WEBHOOK: ${{ secrets.SLACK_GITHUB_NEWISSUEPR }}
                SLACK_MESSAGE: "🐛 New Issue 🐛 by ${{github.actor}}\n [${{github.event.issue.title}}](${{github.event.issue.html_url}}) \n **Description**: \n ${{github.event.issue.body}}"
            - if: github.event_name == 'pull_request' && github.actor != 'asyncapi-bot' && github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]'
              name: Send info about pull request
              uses: Ilshidur/action-slack@2.0.2
              env:
                SLACK_WEBHOOK: ${{ secrets.SLACK_GITHUB_NEWISSUEPR }}
                SLACK_CUSTOM_PAYLOAD: '{"mrkdwn_in":["text","title"],"title":"💪 New pull request 💪 by ${{github.actor}}","text":"[${{github.event.pull_request.title}}](${{github.event.pull_request.html_url}}) \n **Description**: \n"}'
