name: Test default branch

on:
  push:
    branches:
      - master
env:
  commitMessage: github.event.commits[0].message
  
jobs:
  test:
    if: |
      ${{ startsWith(github.repository, 'asyncapi/') && 
      (startsWith($commitMessage, 'fix:') ||
      startsWith($commitMessage, 'fix!:') ||
      startsWith($commitMessage, 'feat:') ||
      startsWith($commitMessage, 'feat!:')) }}
    name: Testing Testing Testing
    runs-on: ubuntu-latest
    steps:
      - run: echo "Wilma! I'm Home $commitMessage"
