name: Test default branch

on:
  push:
    branches:
      - ${{ github.event.repository.default_branch }}

jobs:
  test:
    name: Testing Testing Testing
    runs-on: ubuntu-latest
    steps:
      - run: echo "Wilma! I'm Home"
