name: "Lint PR Title"

on:
  issues:
    types:
            - opened

jobs:
  pre-step:
    #if: contains(github.event.issue.repository.topics, 'nodejs')
    name: set some env
    runs-on: ubuntu-latest
    steps:
      - name: output
        run: echo ::set-output name=exists::false
      - name: set
        run: echo ${{github.event.repository.topics}}
      - name: go
        run: echo ${{github.event.repository}}
  main:
    needs: 
      pre-step:
        outputs:
          exists: true
    name: grr
    runs-on: ubuntu-latest
    steps:
      - run: echo "dupa
