name: Test default branch

on:
  push:
    branches:
      - master

jobs:
  test:
    if: |
      startsWith( github.repository, 'derberg/' ) && 
      (startsWith( github.event.commits[0].message , 'fix:' ) ||
      startsWith( github.event.commits[0].message, 'fix!:' ) ||
      startsWith( github.event.commits[0].message, 'feat:' ) ||
      startsWith( github.event.commits[0].message, 'feat!:' ))
    name: Testing Testing Testing
    runs-on: ubuntu-latest
    steps:
      - run: echo "Wilma! I'm Home ${{github.event.commits[0].message}}"
