name: Test

on:
  issue_comment:
    types:
      - created
jobs:
  test:
    name: Testing Testing Testing
    runs-on: ubuntu-latest
    steps:
      - name: experiment
        uses: derberg/.github-asyncapi/.github/actions/slackify-markdown@bfaffbf653627c9aa23c9a59683d4530ae73f5ea
        id: experiment
        with:
          markdown: "[${{github.event.issue.title}}](${{github.event.comment.html_url}}) \n ${{github.event.comment.body}}"
      - name: get output
        run: echo "${{ steps.experiment.outputs.text }}"
