name: Test default branch

on:
  push:
    branches:
      - master

jobs:
  test:
    if: ${{ !startsWith(fromJson('["fix:", "feat:", "fix!:", "feat!:"]'), github.event.push.commits[0].message) }}
    name: Testing Testing Testing
    runs-on: ubuntu-latest
    steps:
      - run: echo "Wilma! I'm Home"
