name: "Lint PR Title"

on:
  issues:
    types:
            - opened

jobs:
  pre-step:
    name: set some env
    runs-on: ubuntu-latest
    steps:
      - name: set
        run: echo "TEST=dupa" >> $GITHUB_ENV
  main:
    name: Follow Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - run: echo $GITHUB_ENV
