name: "Lint PR Title"

on:
  issues:
    types:
            - opened

jobs:
  pre-step:
    if: contains(github.event.issue.repository.topics, 'nodejs')
    name: set some env
    runs-on: ubuntu-latest
    steps:
      - name: set
        run: echo "TEST=dupa" >> $GITHUB_ENV
      - run: echo ${{env.TEST}}
  main:
    needs: pre-step
    name: grr
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{env.TEST}}
