name: Test

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Testing Testing Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: experiment
        uses: ./.github/actions/slackify-markdown
        id: experiment
        with:
          markdown: |
            *dupa*
 
            - dupa
            - dupa
            - dupa
      - name: get output
        run: echo "${{ steps.experiment.outputs.text }}"
