name: Test default branch

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Testing Testing Testing
    runs-on: ubuntu-latest
    steps:
      - name: experiment
        uses: apache/airflow/.github/actions/breeze@77c272e6e8ecda0ce48917064e58ba14f6a15844
